### ISSUE TITLE
Allow user to specify directory in path

### ISSUE THREAD

**Issue by himynamesdave** [muchdogesec/file2txt#4]
e.g. 

```
python3 file2txt.py \
  --mode pdf \
  --file tests/files/pdf/fanged_data_good.pdf \
  --output examples/fanged_data_good.pdf \
  --defang true \
  --extract_text_from_image false \
  --ai_prettify true
```

gives the error

```
2024-07-07 08:53:38,571 DEBUG request_id: req_86bdb9ead130f44ada1430d068cc78d4
2024-07-07 08:53:38,575 INFO conversion successful
2024-07-07 08:53:38,575 ERROR ran into an exception while parsing: [Errno 2] No such file or directory: 'examples/fanged_data_good.pdf'.
2024-07-07 08:53:38,575 ERROR see /Users/dgreenwood/Documents/repos/dogesec/file2txt/logs/file2txt_20240707-085330_742911.log for more info
2024-07-07 08:53:38,576 DEBUG [Errno 2] No such file or directory: 'examples/fanged_data_good.pdf'
Traceback (most recent call last):
  File "/Users/dgreenwood/Documents/repos/dogesec/file2txt/file2txt.py", line 95, in <module>
    output_file.write_text(BaseParser.PAGE_SEPARATOR.join(output))
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1078, in write_text
    with self.open(mode='w', encoding=encoding, errors=errors, newline=newline) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.6/Frameworks/Python.framework/Versions/3.11/lib/python3.11/pathlib.py", line 1044, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'examples/fanged_data_good.pdf'
2024-07-07 08:53:38,649 DEBUG close.started
2024-07-07 08:53:38,649 DEBUG close.complete
2024-07-07 08:53:38,721 INFO removing temp dir at /var/folders/xb/_snhq4792s9g4lmrg3cy_q480000gn/T/file2txt_cwao1rj3
```

**Comment by himynamesdave** [comment]
@fqrious why is it no longer relevant? Surely a user will still want to be able to dictate output path manually in some cases?

**Comment by fqrious** [comment]
a user could already specify directory, the reason that failed was because examples folder did not exist. Also, now you no longer get to specify output file but output directory, as we're extracting all images along with the markdown file
